### PR TITLE
Use bundled `bootstrap.min.css`

### PR DESCRIPTION
**Pull request by tamarinkeisari**
Import Bootstrap CSS Locally

Description: This pull request modifies the project to import the Bootstrap CSS file directly from the node_modules directory, replacing the current dependency on the CDN link.

Summary of Changes
This update addresses the feature request to enhance the project's ability to function in isolated environments without internet access by importing Bootstrap CSS locally. The following changes have been made:

-   Remove CDN Link
-   Local Bootstrap Import:
        Added an import statement for bootstrap.min.css in src/index.tsx.

we test it locally in it seems to run fine

Related issue:
[#144 ](https://github.com/projectnessie/nessie-ui/issues/144)

### CODE REVIEW

**Comment by snazy** [comment]
@tamarinkeisari thanks for the contribution!
Looks like CI (build) is not happy with your change, can you take a look?

**Comment by tamarinkeisari** [comment]
Hi, @snazy 
The ESlint is configured with the import/no-internal-modules option which prevents importing the bootstrap min css from the node modules. Should we add an eslint ignore on the import?

**Comment by snazy** [comment]
> The ESlint is configured with the import/no-internal-modules option which prevents importing the bootstrap min css from the node modules. Should we add an eslint ignore on the import?

Works for me. But only for that file.

**Comment by tamarinkeisari** [comment]
I disabled the eslint rule for that import line like we discussed

**Comment by snazy** [comment]
Can you also fix the 2nd build issue?

**Comment by tamarinkeisari** [comment]
Hi, after I run npm run lint the build works, but the linting changes a lot of files in the project that are not related to the PR.
Do you want me to upload these unrelated fixes?

**Comment by snazy** [comment]
@tamarinkeisari only the one that lets CI fail

**Comment by tamarinkeisari** [comment]
I uploaded the fix, please let me know if there is anything else to do?

**Comment by snazy** [comment]
Looks like you haven't signed the CLA yet.

**Comment by tamarinkeisari** [comment]
Signed :)

**Review by snazy — APPROVED** [review]
LGTM

**Comment by snazy** [comment]
@tamarinkeisari sorry, we not be able include this change in Nessie yet. There's something odd there.

I'm not sure whether it's your change or something else. The UI looks different.

Previous nessie-ui release 0.63.6:
image

0.64.0:
image

**Comment by snazy** [comment]
Can confirm - it's from your change.

nessie-ui from commit 4d132d9096f6c06cbfc84174bc758be10e968ae1 looks fine:
image

**Pull request merged**
